[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next-runtime"

# Optional: fallback for all unmatched routes (recommended)
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
